### PR TITLE
Development

### PR DESCRIPTION
**Pull request by angel-mora**
# Bubble sort project - first Microverse Ruby project

This repository contains two methods of bubble sort algorithm, one for numbers and another one for words. Both versions are working properly and all changes addressed.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Pull Request has meaningful title and a short description


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by mcrd25 — APPROVED** [review]
# Changes Approve! 💪 🚀 

Hi Team! 👋 

You've successfully implemented changes required from first review! 💪 😄 

However, I'd like to call your attention to one thing moving forward:
Ideally, this project would not have been reviewed because Git-flow was not followed as it should be.
This was mentioned in the project description in pathwright: 
invalid-git-flow

***How Git Flow Works***
  - You'd have the `master` branch purely for production purposes 
  - the `development` branch would act as the main working branch where you create merge requests from `feature` branches to `development` for reviews on these requests
  - If you are requesting a review for a project without multiple milestones simply have one main `feature` branch (appropriately named) that you can then branch off from and merge to accordingly as you complete your project. 
  - After you have completed your project and it's ready for your first review you can then request a code review form your main `feature` branch to `development` branch
  - Once the pull request is approved you can then merge this pull request
  - You would then merge the `development` branch to `master` branch 

For Git- Flow, basically, you will have feature branch merge request into `development` branch and submit a new review on that PR!

Great job with the project! Though! 🚀 

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

**Comment by AdedayoOpeyemi** [comment]
Hi Maya,

Thanks for the review of the project.

However, I would want to point out that Gitflow is not required until the Enumerables project. The details you pointed to above are for the Enumerables project. Below is a screenshot of the requirement for the Bubble sort project. 

image


I will go ahead to submit a new pull request, with the hope that this has been clarified.

Thanks
Opeyemi

**Pull request merged**
